### ISSUE TITLE
Build failure with NullPointerException on first wal file

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/quake2-gwt-port#35]
```
{{{
     [java] players/female/brianna.pcx
     [java] Opened packfile /home/delan/build/quake2-gwt-port/raw/baseq2/pak0.pak (1106 files)
     [java] 
     [java] pics/p_megahealth.pcx
     [java] models/weapons/g_machn/skin.pcx
     [java] models/monsters/soldier/skin_ss.pcx
     [java] pics/w_chaingun.pcx
     [java] models/items/keys/red_key/tris.md2
     [java] textures/e1u1/damage1_2.wal
     [java] Exception in thread "main" java.lang.NullPointerException
     [java]     at jake2.qcommon.Compatibility.newString(Compatibility.java:51)
     [java]     at jake2.qcommon.qfiles$miptex_t.<init>(qfiles.java:367)
     [java]     at jake2.qcommon.qfiles$miptex_t.<init>(qfiles.java:357)
     [java]     at jake2.tools.WALConverter.LoadWAL(WALConverter.java:41)
     [java]     at jake2.tools.WALConverter.convert(WALConverter.java:36)
     [java]     at jake2.tools.Unpak.convertFile(Unpak.java:133)
     [java]     at jake2.tools.Unpak.unpak(Unpak.java:237)
     [java]     at jake2.tools.Unpak.convertDir(Unpak.java:100)
     [java]     at jake2.tools.Unpak.main(Unpak.java:88)
     [java]     at jake2.tools.Installer.main(Installer.java:37)
}}}

Ubuntu 10.10 (maverick), ant 1.8.0-4, openjdk-6-jdk 6b20-1.9.1-1ubuntu3
```

---

Original issue reported on code.google.com by `delan.az...@gmail.com` on 31 Oct 2010 at 12:55

**Comment by GoogleCodeExporter** [comment]
```
The NPE at jake2.qcommon.Compatibility.newString should be fixed by the patch 
attached here: 
http://code.google.com/p/quake2-gwt-port/issues/detail?id=34
Please comment there if it helps you and vote for it.
```

---

Original comment by `DerK...@gmail.com` on 31 Oct 2010 at 1:52

**Comment by GoogleCodeExporter** [comment]
```
The Patch did not work for me for some unrelated reason however I found that 
you only need to add 3 lines from the aforementioned patch in to 
src/jake2/tools/Installer.java from the top of the page

 package jake2.tools;
+import jake2.gwt.server.CompatibilityImpl;
+import jake2.qcommon.Compatibility;
 import java.io.File;

 public class Installer {
   public static void main(String args[]) throws Throwable {
+   Compatibility.impl = new CompatibilityImpl();
     Downloader.main(args);

```

---

Original comment by `ebbe...@googlemail.com` on 15 Nov 2010 at 2:39

**Comment by GoogleCodeExporter** [comment]
```
Hello,

Adding the 3 lines to installer.java worked fine for me too. But I also had to 
remove folders war/baseq2 and raw/baseq2 before rebuild. If not, the sistem 
find existing directory and go on buiding without downloading and unpacking 
necesary files, which leads to black screen failure on browser.
```

---

Original comment by `gaucor...@gmail.com` on 30 Dec 2010 at 10:46

**Comment by GoogleCodeExporter** [comment]
```
Those three lines fixed this problem for me using Ubuntu 10.04 server. I then 
used

   sudo ant clean-resources

to remove the old war/baseq2 and raw/baseq2 directories so the subsequent

   sudo ant run

installed them correctly.
```

---

Original comment by `steamlan...@gmail.com` on 6 Apr 2011 at 4:37

**Comment by GoogleCodeExporter** [comment]
```
Comment 2 fixed the issue with me on my 10.4 64-bit ubuntu.
```

---

Original comment by `maescool` on 1 May 2011 at 6:07

**Comment by GoogleCodeExporter** [comment]
```
Comment 2 also fixes the issue on fedora 14 64bit.
```

---

Original comment by `gurket...@googlemail.com` on 2 Aug 2011 at 7:55

**Comment by GoogleCodeExporter** [comment]
```
fixed as suggested
```

---

Original comment by `stefan.haustein` on 11 Oct 2011 at 6:41
- Changed state: **Fixed**
