### ISSUE TITLE
Following Wiki - openJdk, lame, oggvorbis installed - Debian Squeeze testing, bug after ant run

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/quake2-gwt-port#37]
```
What steps will reproduce the problem?
1. Follow all steps on wiki with Debian Squeeze
2. Run : ant run in the quake2-gwt folder
3. Exception in thread "main" java.lang.NoClassDefFoundError: 

What is the expected output? What do you see instead?

root@nox:/home/nox/quake2-gwt-port# ant run
Buildfile: /home/nox/quake2-gwt-port/build.xml

libs:

server:
    [javac] /home/nox/quake2-gwt-port/build.xml:57: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds

install-resources:
     [java] raw/baseq2 already exists; no need to download
     [java] war/baseq2 already exists; no need to unpak

client.build:

libs:

server:
    [javac] /home/nox/quake2-gwt-port/build.xml:57: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds

client.run:

build:

run:
     [java] 2010-12-03 23:30:47.413:INFO::jetty-8.0.0.M2-SNAPSHOT
     [java] 2010-12-03 23:30:47.485:INFO::Started SelectChannelConnector@0.0.0.0:8080
     [java] couldn't exec config.cfg
     [java] couldn't exec config.cfg
     [java] Exception in thread "main" java.lang.NoClassDefFoundError: jake2/gwt/server/ServerWebSocketImpl
     [java]     at jake2.gwt.server.ServerWebSocketFactoryImpl.bind(ServerWebSocketFactoryImpl.java:41)
     [java]     at jake2.sys.NET.Socket(NET.java:337)
     [java]     at jake2.sys.NET.OpenIP(NET.java:285)
     [java]     at jake2.sys.NET.Config(NET.java:315)
     [java]     at jake2.server.SV_INIT.SV_InitGame(SV_INIT.java:371)
     [java]     at jake2.server.SV_INIT.SV_Map(SV_INIT.java:413)
     [java]     at jake2.server.SV_CCMDS.SV_GameMap_f(SV_CCMDS.java:612)
     [java]     at jake2.server.SV_CCMDS.SV_Map_f(SV_CCMDS.java:643)
     [java]     at jake2.server.SV_CCMDS$8.execute(SV_CCMDS.java:1091)
     [java]     at jake2.game.Cmd.ExecuteString(Cmd.java:408)
     [java]     at jake2.qcommon.Cbuf.Execute(Cbuf.java:203)
     [java]     at jake2.qcommon.Qcommon.Init(Qcommon.java:139)
     [java]     at jake2.server.QuakeServer.run(QuakeServer.java:61)
     [java]     at jake2.gwt.server.GwtQuakeServer.main(GwtQuakeServer.java:66)
     [java] Caused by: java.lang.ClassNotFoundException: jake2.gwt.server.ServerWebSocketImpl
     [java]     at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
     [java]     at java.security.AccessController.doPrivileged(Native Method)
     [java]     at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
     [java]     at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
     [java]     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
     [java]     at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
     [java]     ... 14 more




```

---

Original issue reported on code.google.com by `thierry....@gmail.com` on 3 Dec 2010 at 10:35

**Comment by GoogleCodeExporter** [comment]
```
I retried from the start, here's all the log : 

root@nox:/home/nox# hg clone https://quake2-gwt-port.googlecode.com/hg/ 
quake2-gwt-port
requesting all changes
adding changesets
adding manifests
adding file changes
added 45 changesets with 952 changes to 522 files (+1 heads)
updating to branch default
451 files updated, 0 files merged, 0 files removed, 0 files unresolved
root@nox:/home/nox# cd quake2-gwt-port/
root@nox:/home/nox/quake2-gwt-port# ant run
Buildfile: /home/nox/quake2-gwt-port/build.xml

libs:
    [mkdir] Created dir: /home/nox/quake2-gwt-port/war/WEB-INF/lib
     [copy] Copying 1 file to /home/nox/quake2-gwt-port/war/WEB-INF/lib

server:
    [mkdir] Created dir: /home/nox/quake2-gwt-port/war/WEB-INF/classes
    [javac] /home/nox/quake2-gwt-port/build.xml:57: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 295 source files to /home/nox/quake2-gwt-port/war/WEB-INF/classes
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
     [copy] Copying 5 files to /home/nox/quake2-gwt-port/war/WEB-INF/classes
     [copy] Copied 13 empty directories to 7 empty directories under /home/nox/quake2-gwt-port/war/WEB-INF/classes

install-resources:
     [java] Trying mirror: ftp://ftp.demon.co.uk/pub/mirrors/idsoftware/quake2/q2-314-demo-x86.exe
     [java] Donwload Failed
     [java] Trying mirror: ftp://ftp.fragzone.se/pub/spel/quake2/q2-314-demo-x86.exe
     [java] Donwload Failed
     [java] Trying mirror: ftp://ftp.idsoftware.com/idstuff/quake2/q2-314-demo-x86.exe
     [java] Downloading.......................................Download finished; uncompressing
     [java] installing /baseq2/pak0.pak
     [java] installing /baseq2/players/female/athena.pcx
     [java] installing /baseq2/players/female/athena_i.pcx
     [java] installing /baseq2/players/female/brianna.pcx
     [java] installing /baseq2/players/female/brianna_i.pcx
     [java] installing /baseq2/players/female/cobalt.pcx
     [java] installing /baseq2/players/female/cobalt_i.pcx
     [java] installing /baseq2/players/female/doomgal.pcx
     [java] installing /baseq2/players/female/doomgal_i.pcx
     [java] installing /baseq2/players/female/ensign.pcx
     [java] installing /baseq2/players/female/ensign_i.pcx
     [java] installing /baseq2/players/female/jezebel.pcx
     [java] installing /baseq2/players/female/jezebel_i.pcx
     [java] installing /baseq2/players/female/jungle.pcx
     [java] installing /baseq2/players/female/jungle_i.pcx
     [java] installing /baseq2/players/female/lotus.pcx
     [java] installing /baseq2/players/female/lotus_i.pcx
     [java] installing /baseq2/players/female/stiletto.pcx
     [java] installing /baseq2/players/female/stiletto_i.pcx
     [java] installing /baseq2/players/female/tris.md2
     [java] installing /baseq2/players/female/venus.pcx
     [java] installing /baseq2/players/female/venus_i.pcx
     [java] installing /baseq2/players/female/voodoo.pcx
     [java] installing /baseq2/players/female/voodoo_i.pcx
     [java] installing /baseq2/players/female/weapon.md2
     [java] installing /baseq2/players/female/weapon.pcx
     [java] installing /baseq2/players/male/cipher.pcx
     [java] installing /baseq2/players/male/cipher_i.pcx
     [java] installing /baseq2/players/male/claymore.pcx
     [java] installing /baseq2/players/male/claymore_i.pcx
     [java] installing /baseq2/players/male/flak.pcx
     [java] installing /baseq2/players/male/flak_i.pcx
     [java] installing /baseq2/players/male/grunt.pcx
     [java] installing /baseq2/players/male/grunt_i.pcx
     [java] installing /baseq2/players/male/howitzer.pcx
     [java] installing /baseq2/players/male/howitzer_i.pcx
     [java] installing /baseq2/players/male/major.pcx
     [java] installing /baseq2/players/male/major_i.pcx
     [java] installing /baseq2/players/male/nightops.pcx
     [java] installing /baseq2/players/male/nightops_i.pcx
     [java] installing /baseq2/players/male/pointman.pcx
     [java] installing /baseq2/players/male/pointman_i.pcx
     [java] installing /baseq2/players/male/psycho.pcx
     [java] installing /baseq2/players/male/psycho_i.pcx
     [java] installing /baseq2/players/male/rampage.pcx
     [java] installing /baseq2/players/male/rampage_i.pcx
     [java] installing /baseq2/players/male/razor.pcx
     [java] installing /baseq2/players/male/razor_i.pcx
     [java] installing /baseq2/players/male/recon.pcx
     [java] installing /baseq2/players/male/recon_i.pcx
     [java] installing /baseq2/players/male/scout.pcx
     [java] installing /baseq2/players/male/scout_i.pcx
     [java] installing /baseq2/players/male/skin.pcx
     [java] installing /baseq2/players/male/sniper.pcx
     [java] installing /baseq2/players/male/sniper_i.pcx
     [java] installing /baseq2/players/male/tris.md2
     [java] installing /baseq2/players/male/viper.pcx
     [java] installing /baseq2/players/male/viper_i.pcx
     [java] installing /baseq2/players/male/weapon.md2
     [java] installing /baseq2/players/male/weapon.pcx
     [java] players/male/major_i.pcx
     [java] players/male/flak_i.pcx
     [java] players/male/claymore_i.pcx
     [java] players/male/sniper_i.pcx
     [java] players/male/howitzer.pcx
     [java] players/male/razor_i.pcx
     [java] players/male/psycho_i.pcx
     [java] players/male/viper.pcx
     [java] players/male/recon_i.pcx
     [java] players/male/sniper.pcx
     [java] players/male/viper_i.pcx
     [java] players/male/scout.pcx
     [java] players/male/grunt_i.pcx
     [java] players/male/skin.pcx
     [java] players/male/major.pcx
     [java] players/male/tris.md2
     [java] players/male/rampage.pcx
     [java] players/male/rampage_i.pcx
     [java] players/male/flak.pcx
     [java] players/male/cipher.pcx
     [java] players/male/pointman_i.pcx
     [java] players/male/pointman.pcx
     [java] players/male/howitzer_i.pcx
     [java] players/male/claymore.pcx
     [java] players/male/nightops.pcx
     [java] players/male/cipher_i.pcx
     [java] players/male/psycho.pcx
     [java] players/male/weapon.pcx
     [java] players/male/razor.pcx
     [java] players/male/recon.pcx
     [java] players/male/nightops_i.pcx
     [java] players/male/grunt.pcx
     [java] players/male/weapon.md2
     [java] players/male/scout_i.pcx
     [java] players/female/voodoo_i.pcx
     [java] players/female/jungle_i.pcx
     [java] players/female/stiletto_i.pcx
     [java] players/female/doomgal_i.pcx
     [java] players/female/athena_i.pcx
     [java] players/female/doomgal.pcx
     [java] players/female/jezebel_i.pcx
     [java] players/female/lotus_i.pcx
     [java] players/female/tris.md2
     [java] players/female/cobalt_i.pcx
     [java] players/female/jungle.pcx
     [java] players/female/ensign_i.pcx
     [java] players/female/lotus.pcx
     [java] players/female/cobalt.pcx
     [java] players/female/brianna_i.pcx
     [java] players/female/weapon.pcx
     [java] players/female/venus.pcx
     [java] players/female/athena.pcx
     [java] players/female/ensign.pcx
     [java] players/female/jezebel.pcx
     [java] players/female/brianna.pcx
     [java] players/female/weapon.md2
     [java] players/female/voodoo.pcx
     [java] players/female/venus_i.pcx
     [java] players/female/stiletto.pcx
     [java] Opened packfile /home/nox/quake2-gwt-port/raw/baseq2/pak0.pak (1106 files)
     [java] 
     [java] pics/p_megahealth.pcx
     [java] models/weapons/g_machn/skin.pcx
     [java] models/monsters/soldier/skin_ss.pcx
     [java] pics/w_chaingun.pcx
     [java] models/items/keys/red_key/tris.md2
     [java] textures/e1u1/damage1_2.wal
     [java] Exception in thread "main" java.lang.NullPointerException
     [java]     at jake2.qcommon.Compatibility.newString(Compatibility.java:51)
     [java]     at jake2.qcommon.qfiles$miptex_t.<init>(qfiles.java:367)
     [java]     at jake2.qcommon.qfiles$miptex_t.<init>(qfiles.java:357)
     [java]     at jake2.tools.WALConverter.LoadWAL(WALConverter.java:41)
     [java]     at jake2.tools.WALConverter.convert(WALConverter.java:36)
     [java]     at jake2.tools.Unpak.convertFile(Unpak.java:133)
     [java]     at jake2.tools.Unpak.unpak(Unpak.java:237)
     [java]     at jake2.tools.Unpak.convertDir(Unpak.java:100)
     [java]     at jake2.tools.Unpak.main(Unpak.java:88)
     [java]     at jake2.tools.Installer.main(Installer.java:37)
```

---

Original comment by `thierry....@gmail.com` on 4 Dec 2010 at 1:00

**Comment by GoogleCodeExporter** [comment]
```
Have a look at #35. This should fix 

     [java] textures/e1u1/damage1_2.wal
     [java] Exception in thread "main" java.lang.NullPointerException
     [java]     at jake2.qcommon.Compatibility.newString(Compatibility.java:51)
```

---

Original comment by `gurket...@googlemail.com` on 2 Aug 2011 at 7:59

**Comment by GoogleCodeExporter** [comment]
```
The compatibility class was not initialized / set; fixed
```

---

Original comment by `stefan.haustein` on 11 Oct 2011 at 6:40
- Changed state: **Fixed**
