### ISSUE TITLE
incompatible pak0.pak ?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/quake2-gwt-port#44]
```
1. copy over my baseq2 files
2. ant build
3. build fails @ pak0.pak
What is the expected output? What do you see instead?
...
...
...
  [java] players/cyborg/weapon.pcx
     [java] video/eou3_.cin
     [java] video/eou2_.cin
     [java] video/eou1_.cin
     [java] video/end.cin
     [java] video/ntro.cin
     [java] video/eou7_.cin
     [java] video/eou5_.cin
     [java] video/eou4_.cin
     [java] video/idlog.cin
     [java] video/eou6_.cin
     [java] video/eou8_.cin
     [java] Exception in thread "main" java.lang.IllegalArgumentException
     [java]     at java.nio.Buffer.position(Buffer.java:235)
     [java]     at jake2.tools.Unpak.loadPackFile(Unpak.java:193)
     [java]     at jake2.tools.Unpak.unpak(Unpak.java:231)
     [java]     at jake2.tools.Unpak.convertDir(Unpak.java:100)
     [java]     at jake2.tools.Unpak.main(Unpak.java:88)
     [java]     at jake2.tools.Installer.main(Installer.java:41)

BUILD FAILED
/home/paige/quake2-gwt-port/build.xml:66: Java returned: 1

Total time: 24 seconds
paige@yggdrasil ~/quake2-gwt-port $


What version of the product are you using? On what operating system?

? latest stable with a patch that helps me get at least this far, also I can 
get it to work with the regular baseq2 (demo) files but it's missing some 
textures and models.

Please provide any additional information below.

Please feel free to inquire
```

---

Original issue reported on code.google.com by `paig...@devel.ws` on 30 Sep 2011 at 3:41

**Comment by GoogleCodeExporter** [comment]
```
maybe this is more of an issue with jake2.tools.Unpak than anything you guys 
would care about, not sure this is all new to me so
```

---

Original comment by `paig...@devel.ws` on 30 Sep 2011 at 3:42

**Comment by GoogleCodeExporter** [comment]
```
this file might come in handy, describes the pak format 
```

---

Original comment by `paig...@devel.ws` on 30 Sep 2011 at 5:03

Attachments:
- [pak-format.txt](https://storage.googleapis.com/google-code-attachments/quake2-gwt-port/issue-44/comment-2/pak-format.txt)

**Comment by GoogleCodeExporter** [comment]
```
Ultimately I decided it would probably make more sense if the build process 
didn't rely on java code to be able to always open the pak file, rather the 
following: 

1. The unpacker extracts the content to a temporary directory or not if no pak 
files are available

2. If there is content in the temporary directory, then convert it

3. the content is converted 

This in theory would give me the option of using a different unpaker (one that 
works) to extract the contents of my pak file and then I can put the content in 
the temporary directory myself and use the conversion tools that are already 
written (because I really don't want to figure out how to convert .cin to mp4 
and because writing a python script to do os.path.walk is pretty easy, I don't 
want to do it if I don't have to.)

```

---

Original comment by `paig...@devel.ws` on 9 Oct 2011 at 5:09

**Comment by GoogleCodeExporter** [comment]
```
There was a bug in convert / unpack, which is fixed now. I hope this solves 
your issue.
```

---

Original comment by `stefan.haustein` on 11 Oct 2011 at 6:42
- Changed state: **Fixed**
