### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/quake2-gwt-port#7]
```
What steps will reproduce the problem?
1. ./run-dedicated-server 1235

What is the expected output? What do you see instead?

"samurailink3@spaghetti:~/working/quake2-gwt-port$ ./run-dedicated-server 1235
2010-04-03 10:22:39.862::INFO:  Logging to STDERR via org.mortbay.log.StdErrLog
2010-04-03 10:22:39.891::INFO:  jetty-6.1.x
2010-04-03 10:22:39.918::WARN:  failed SocketConnector@0.0.0.0:8080
java.net.BindException: Address already in use"

What version of the product are you using? On what operating system?

Ubuntu 9.10 (x64) - 2.6.31-20-generic

Please provide any additional information below.

Attempted with and without root privileges. Attempted multiple ports.
Killed all other java applications, same error resulted.
```

---

Original issue reported on code.google.com by `samurailink3` on 3 Apr 2010 at 3:28

**Comment by GoogleCodeExporter** [comment]
```
Why are you putting "1235" after the command?  Are you trying to change the 
port?  It 
clearly doesn't understand your "1235" and still tries to use 8080.
```

---

Original comment by `megazzt` on 3 Apr 2010 at 3:30

**Comment by GoogleCodeExporter** [comment]
```
I assumed that the instructions were to specify a port:
"./run-dedicated-server [port]" (From:
http://code.google.com/p/quake2-gwt-port/wiki/BuildingAndRunning)

I was attempting to run on port 1235, I have tried with 8080 instead, and with 
the
bare command as well [./run-dedicated-server], but it still gives the same 
error.
```

---

Original comment by `samurailink3` on 3 Apr 2010 at 3:33

**Comment by GoogleCodeExporter** [comment]
```
The bug isn't really address already in use. If the server can't bind to 8080 
it's because that port is in use. The 
bug is that the command ./run-dedicated-server ignores the port given.

It's because the ./run-dedicated-server script ignores the address passed.

To fix it modify the startup script.
do this:
$nano run-dedicated-server
Then change the 2nd line so that it looks like this:
java -jar maven-build/server/target/gwtquake/gquake-server-1.0-SNAPSHOT.jar $1

All you do is ad the $1
```

---

Original comment by `Giovanni...@gmail.com` on 3 Apr 2010 at 3:49

**Comment by GoogleCodeExporter** [comment]
```
Wow... that was incredibly easy. Everything's shiny, Cap'n, not to fret!!

Thanks a ton for the help!
```

---

Original comment by `samurailink3` on 3 Apr 2010 at 3:58

**Comment by GoogleCodeExporter** [comment]
```
When I type in terminal:
#/.run-dedicated-server
I get Error:
Server started
==== ShutdownGame ====
==== InitGame ====
------- Server Initialization -------
====== Quake2 Initialized ======

java.io.FileNotFoundException: maps/demo1.bsp
    at jake2.desktop.ResourceLoaderImpl.pump(ResourceLoaderImpl.java:65)
    at jake2.qcommon.ResourceLoader.Pump(ResourceLoader.java:36)
    at jake2.server.QuakeServer.run(QuakeServer.java:76)
    at jake2.gwt.server.GwtQuakeServer.main(GwtQuakeServer.java:68)
Please help me ..
```

---

Original comment by `Duonguno...@gmail.com` on 3 Apr 2010 at 5:03

**Comment by GoogleCodeExporter** [comment]
```
"I assumed that the instructions were to specify a port"  Whoops, you're right, 
my apologies.

@duonguno Try running step 4 again here: http://code.google.com/p/quake2-gwt-
port/wiki/BuildingAndRunning and be sure not to forget the bullet point below 
it!
```

---

Original comment by `megazzt` on 5 Apr 2010 at 12:31

**Comment by GoogleCodeExporter** [comment]
```
committed GiovanniZero's fix to hg
```

---

Original comment by `stefan.haustein` on 9 Apr 2010 at 8:29
- Changed state: **Fixed**
